export const projects = [
    {
      title: "Face Recognition",
      subtitle: "React, NodeJS and PostgreSQL",
      description:
        "Robocards is a full stack project. This is a facial recognition system that uses an API developed by Clarifai. New users can join, and a counter indicates how many times the system has been used by each member.",
      image: "./smart-brain.gif",
      link: "https://smart-brain-enahum.herokuapp.com/",
      github: "https://github.com/enahum0412/smart-brain"
    },
    {
      title: "Robocards",
      subtitle: "React",
      description:
        "Robocards is a React project made for the purpose of research and study. It is an instant search box that selects cards from the list initially displayed on the page.",
      image: "./robofriends.gif",
      link: "https://enahum-robocards.netlify.app/",
      github: "https://github.com/enahum0412/robofriends"
    },
    {
      title: "Background Generator",
      subtitle: "JavaScript",
      description:
        "Background Generator is a JavaScript project. With input color, the user can select a linear gradient background directly in the browser and use the automatically CSS code generated by the app.",
      image: "./background-generator.gif",
      link: "https://enahum-background-generator.netlify.app/",
      github: "https://github.com/enahum0412/background-generator"
    },
    {
      title: "Sports Page",
      subtitle: "JavaScript",
      description:
        "Sports Page is a simple HTML/CSS + Vanilla JavaScript project created as a model, using other websites concepts as inpiration. It is an example of front page made for the purpose of research to apply my knowledge.",
      image: "./sports-page.gif",
      link: "https://sports-page.netlify.app/",
      github: "https://github.com/enahum0412/sports-page"
    },
    {
      title: "Form Validator",
      subtitle: "JavaScript",
      description:
        "Form Validator is a simple example of a HTML/CSS + Vanilla JavaScript project created as a model. It is an example made for the purpose of research and study to apply my knowledge in the mentioned languages.",
      image: "./form-vaidator.gif",
      link: "https://form-validator-vanillajs.netlify.app/",
      github: "https://github.com/enahum0412/form-validator"
    },
    {
      title: "Relaxer App",
      subtitle: "JavaScript",
      description:
        "Relaxer is a simple example of a HTML/CSS + Vanilla JavaScript project created as a model. It is an example made for the purpose of research and study to apply my knowledge in the mentioned languages.",
      image: "./relaxer.gif",
      link: "https://relaxer-click.netlify.app/",
      github: "https://github.com/enahum0412/relaxer-click"
    },
    {
      title: "ENOF Firm",
      subtitle: "HTML and CSS",
      description:
        "ENOF Firm is a simple example of a simple HTML/CSS page created as a model. It is a fake, example only, made for a College presentation at Montreal, QC.",
      image: "./enof-firm.gif",
      link: "https://enof-firm.netlify.app/",
      github: "https://github.com/enahum0412/enof-firm"
    },
  ];

  export const frontSkills = [
    "HTML",
    "CSS",
    "JavaScript",
    "React.js"
  ]

  export const backSkills = [
    "Node.js",
    "PostgreSQL",
    "MySQL",
    "Java"
  ]

  export const otherSkills = [
    "Git / GitHub",
    "Npm",
    "WordPress",
    "Responsive Design"
  ]

  // export const skills = [
  //   "JavaScript",
  //   "React",
  //   "HTML",
  //   "CSS",
  //   "Node.js",
  //   "PostgreSQL",
  // ];

  // export const testimonials = [
  //   {
  //     quote:
  //       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa quod necessitatibus quidem impedit facilis? Distinctio laboriosam veritatis recusandae minus. Voluptatum accusantium hic laudantium soluta ea sapiente cupiditate officia maiores itaque.",
  //     image: "https://randomuser.me/api/portraits/men/1.jpg",
  //     name: "Jesse Hicks",
  //     company: "Zoozle",
  //   },
  //   {
  //     quote:
  //       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa quod necessitatibus quidem impedit facilis? Distinctio laboriosam veritatis recusandae minus. Voluptatum accusantium hic laudantium soluta ea sapiente cupiditate officia maiores itaque.",
  //     image: "https://randomuser.me/api/portraits/men/94.jpg",
  //     name: "Ruben Alvarez",
  //     company: "Dooble.io",
  //   },
  // ];